### ISSUE TITLE
Issue with Chromium version and docker-compose

### ISSUE THREAD

**Issue by RajaBellebon** [gidztech/jest-puppeteer-docker#13] opened 2018-12-23 23:42 UTC
Hello @gidztech ,

I did not change anything to my setup but now I am facing issues while running my test **locally**:

    Jest Puppeteer Docker: Setting Chromium version to rev-609904...
    Jest Puppeteer Docker: Building Docker image...
    { Error: Command failed: docker-compose -f "/Users/rbellebon/atlaskit-mk-2/node_modules/jest- 
    puppeteer-docker/docker-compose.yml" build --pull
    Building chromium
    Service 'chromium' failed to build: manifest for alpeware/chrome-headless-trunk:rev-609904 not 
    found

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
    killed: false,
    code: 1,
    signal: null,
    cmd: 'docker-compose -f "/Users/rbellebon/atlaskit-mk-2/node_modules/jest-puppeteer-docker/docker-compose.yml" build --pull',
    stdout: 'Step 1/7 : FROM alpeware/chrome-headless-trunk:rev-609904\n',
    stderr: 'Building chromium\nService \'chromium\' failed to build: manifest for alpeware/chrome-headless-trunk:rev-609904 not found\n' }
 

any idea?

Something else, we faced lot of issues in CI (we use bitbucket pipelines...)

`Error: Command failed: docker-compose -f "/opt/atlassian/pipelines/agent/build/node_modules/jest-puppeteer-docker/docker-compose.yml" up -d
docker: Error response from daemon: authorization denied by plugin pipelines: -v only supports $BITBUCKET_CLONE_DIR and its subdirectories.
See 'docker run --help'.
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
  killed: false,
  code: 125,
  signal: null,
  cmd: 'docker-compose -f "/opt/atlassian/pipelines/agent/build/node_modules/jest-puppeteer-docker/docker-compose.yml" up -d',
  stdout: '',
  stderr: 'docker: Error response from daemon: authorization denied by plugin pipelines: -v only supports $BITBUCKET_CLONE_DIR and its subdirectories.\nSee \'docker run --help\'.\n' }`

**Comment by RajaBellebon** [comment] 2018-12-28 07:06
Hello @gidztech  any updates on this one I keep getting this error...

**Comment by gidztech** [comment] 2018-12-28 11:35
Hi there. I’ll try and take a look at this later today.

**Comment by gidztech** [comment] 2018-12-28 19:51
The issue here is that the Docker image with revision 609904 doesn't exist in the hub. 3 builds were skipped according to this automated commit. https://github.com/alpeware/chrome-headless-trunk/commit/2cb87cff180242366eadd7816a8b03abb36ae339

I had this issue recently, probably the same version, so I added some fallback logic to build the image from scratch in the case that the image doesn't exist in Docker Hub. That should solve the first issue.

As for the second issue, I set up Bitbucket Pipeline and found the issue for me was the Docker capabilities I added for networking. Bitbucket doesn't allow it for some security reasons. It turns out I don't actually need it (at least my tests pass anyway), so I removed them. I was able to get a successful build with Bitbucket thereafter, so hopefully that is now fixed.

I've published a new version.

**Closed** 2018-12-28 19:58 UTC

**Comment by RajaBellebon** [comment] 2018-12-29 06:09
@gidztech Thanks a lot, I'll have a look soon!

**Comment by gidztech** [comment] 2019-01-05 02:38
The first issue is because of a string linting rule. You should be able to import dev dependencies if they are in test files or build scripts. You can set something like the following rule in your `.eslintrc` file to ignore the rule in files that match the glob pattern:

```
"import/no-extraneous-dependencies": ["error", {"devDependencies": ["**/*.test.js", "**/*.spec.js"]}]
```

The second issue is a regression when I split up the repository. That has now been fixed in v.1.1.1, and I've added some test coverage around config.
